NAME = book

src = InitBook.cpp Main.cpp InitContact.cpp Utils.cpp

hd = PhoneBook.hpp

flags = -Wall -Wextra -Werror -std=c++98

c = c++

all: $(NAME)

$(NAME): $(src) $(hd)
	$(c) $(flags) $(src) -o $(NAME)

clean:
	rm -rf $(NAME)

fclean: clean

re: fclean all