NAME = Zombie

src = main.cpp newZombie.cpp randomChump.cpp Zombie.cpp

hd = Zombie.hpp

flags = -Wall -Wextra -Werror -std=c++98

c = c++

all: $(NAME)

$(NAME): $(src) $(hd)
	$(c) $(flags) $(src) -o $(NAME)

clean:
	rm -rf $(NAME)

fclean: clean

re: fclean all